name: Mixins

on:
  pull_request:
    branches:
      - main

jobs:
  mixins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Render mixins
        run: make

      - name: Check for changed mixins
        run: |
          if [[ $(git status --short docs | wc -l) -ne 0 ]]; then
            echo "Detected changes in the rendered docs files. Please run 'make' locally and commit the changes."
            git status --short docs
            exit 1
          fi
        id: status
