name: Mixins

on:
  pull_request:
    branches:
      - main

jobs:
  mixins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Render mixins
        run: make

      - name: Check for changes
        run: echo "changed=$(git status --short docs | wc -l)" >> "$GITHUB_OUTPUT"
        id: status

      - name: Detected changes
        if: ${{ steps.status.outputs.changed !=0 }}
        run: |
          echo "::error::Detected changes in the rendered docs files. Please run 'make' locally and commit the changes."
          git status --short docs
          exit 1
